# Generated by Django 3.2.25 on 2024-05-21 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='genre',
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalogue.Category'),
        ),
        migrations.AlterField(
            model_name='toolinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tool across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='tool availability', max_length=1),
        ),
    ]
